#!/bin/bash

# 2.1 Setup basic prefix for the naming convention
export PREFIX="ec2-cli-demo-${RANDY}"

# 2.2 - Obtain latest release name of Ubuntu Focal
export LATEST_UR=$(aws ec2 describe-images \
  --owners 099720109477 \
  --filters "Name=name,Values=*minimal*hvm-ssd*focal*20*-amd64*2023*" \
  --query 'sort_by(Images, &CreationDate)[].Name' \
  | jq -r '.[length-1]')

# 2.3 Obtain the AWS AMI ID to create a new EC2 instance
export IMAGE_ID=$(aws ec2 describe-images \
  --owners 099720109477 \
  --filters "Name=name,Values=${LATEST_UR}" \
  --query 'sort_by(Images, &CreationDate)[].ImageId' \
  | jq -r '.[]')

 # 2.3 Create an SSH Key to access the new EC2 instance
aws ec2 create-key-pair \
  --key-name $PREFIX \
  --query 'KeyMaterial' \
  --output text > "${PREFIX}.pem"

# 2.3.1 Safe permissions for EC2 Key
chmod 400 "${PREFIX}.pem"

# 2.4 We need to declare an AWS EC2 security group
aws ec2 create-security-group \
--group-name $PREFIX \
--description "EC2 CLI Demo"

# 2.5 Obtain the unique ID for the new security group
export AWS_DEFAULT_SG=$(aws ec2 describe-security-groups \
--group-name $PREFIX \
| jq -r '.SecurityGroups[].GroupId')

# 2.6 Open HTTP port 22 to the whole world
aws ec2 authorize-security-group-ingress \
--group-id $AWS_DEFAULT_SG \
--protocol tcp \
--port 22 \
--cidr 0.0.0.0/0

# 2.6 Open HTTP port 80 to the whole world
aws ec2 authorize-security-group-ingress \
--group-id $AWS_DEFAULT_SG \
--protocol tcp \
--port 80 \
--cidr 0.0.0.0/0

# 2.7 Launch a bare bones, free-range, glutten-free
# AWS EC2 instance
export LATEST_EC2_INSTANCE=$(aws ec2 run-instances \
--image-id $IMAGE_ID \
--instance-type t2.micro \
--associate-public-ip-address \
--key-name $PREFIX \
--security-group-ids $AWS_DEFAULT_SG)

export EC2_INSTANCE_ID=$(echo $LATEST_EC2_INSTANCE \
  | jq -r '.Instances | .[].InstanceId')

export EC2_INSTANCE_IP=$(aws ec2 describe-instances \
  --filters "Name=instance-type,Values=t2.micro" \
  --filters "Name=tag:Name,Values=${PREFIX}" \
  --filters "Name=instance-state-name,Values=running" \
  | jq -r '.Reservations | .[].Instances | .[].PublicIpAddress')

ssh -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -i "/root/${PREFIX}.pem" \
  ubuntu@$EC2_INSTANCE_IP < /root/bash/deploy-app.sh

export URL="http://${EC2_INSTANCE_IP}"

echo $URL

exit 0
