#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

export WORKING_DIR=/root/terraform/01
cd $WORKING_DIR
terraform init 
terraform apply -auto-approve

exit 0
